version: '2.1'
services:
  configuration-server:
    container_name: configuration-server
    hostname: configuration-server
    image: dev-it/devit-configuration-server:latest
    expose:
    - 8888
    ports:
    - 8888:8888
    networks:
    - devit-network
    environment:
    - eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
    depends_on:
    - eureka
    links:
    - eureka
    logging:
      driver: json-file

networks:
  devit-network:
    driver: bridge